const actions = {
    REQUEST_START: 'REQUEST_START',
    REQUEST_ERROR: 'REQUEST_ERROR',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    REQUEST_STARTPOINT: 'REQUEST_STARTPOINT',
    REQUEST_DESTINATION: 'REQUEST_DESTINATION',
}

export default actions
